# .sync.yml
---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
      - gem: 'nokogiri'
      - gem: 'savon'
      - gem: 'coveralls'
spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - "require 'coveralls'"
    - "Coveralls.wear!"
